# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='_shui_1',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='_shui_2',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='_shui_3',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='_wen_1',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='_wen_2',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='_wen_3',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
