# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showdata', '0003_remove_data__router'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='_router',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='_addr',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='_info',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='_kong',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='_state',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='_volt',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
