# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showdata', '0004_auto_20171203_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='_addr',
            new_name='addr',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='_info',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='_kong',
            new_name='kong',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='_router',
            new_name='router',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='_shui_1',
            new_name='shui_1',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='_shui_2',
            new_name='shui_2',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='_shui_3',
            new_name='shui_3',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='_volt',
            new_name='volt',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='_wen_1',
            new_name='wen_1',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='_wen_2',
            new_name='wen_2',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='_wen_3',
            new_name='wen_3',
        ),
    ]
