# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showdata', '0005_auto_20171203_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='addr',
            new_name='_01addr',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='info',
            new_name='_02name',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='time',
            new_name='_03time',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='shui_1',
            new_name='_04shui_1',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='shui_2',
            new_name='_05wen_1',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='shui_3',
            new_name='_06shui_2',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='wen_1',
            new_name='_07wen_2',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='wen_2',
            new_name='_08shui_3',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='wen_3',
            new_name='_09wen_3',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='name',
            new_name='_10state',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='router',
            new_name='_11info',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='state',
            new_name='_12volt',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='kong',
            new_name='_13kong',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='volt',
            new_name='_14router',
        ),
    ]
