# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showdata', '0008_auto_20171204_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=25, null=True, verbose_name='设备地址')),
                ('name', models.CharField(max_length=25, null=True, verbose_name='测站名称')),
            ],
            options={
                'ordering': ['addr', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='File')),
                ('name', models.CharField(max_length=60, verbose_name='文件名')),
            ],
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['addr', 'name', 'time']},
        ),
        migrations.AlterField(
            model_name='data',
            name='addr',
            field=models.CharField(max_length=25, null=True, verbose_name='设备地址'),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=25, null=True, verbose_name='测站名称'),
        ),
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.CharField(max_length=25, null=True, verbose_name='采集时间'),
        ),
    ]
